#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-gatus
- name: Ensure image is pulled
  containers.podman.podman_image:
    name: "{{ gatus_image }}"
    tag: "{{ gatus_image_tag }}"
  register: pulled
  become_user: "{{ rootless_user }}"

- name: Remove existing container if image has changed
  containers.podman.podman_container:
    name: "{{ gatus_container }}"
    state: absent
  when: pulled.changed
  become_user: "{{ rootless_user }}"

- name: Ensure /etc/gatus/ directory exists
  file:
    path: /etc/gatus
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: '0755'

- name: Copy template to host 
  template:
    src: templates/config.yml.j2
    path: /etc/gatus/config.yml
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: '0444'
