#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-gatus
- name: Ensure image is pulled
  community.podman.podman_image:
    name: "{{ gatus_image }}"
  register: pulled

- name: Remove existing container if image has changed (Podman)
  community.podman.podman_container:
    name: "{{ podman_container }}"
    state: absent
  when: pulled.changed

- name: Ensure /etc/gatus/ directory exists
  file:
    path: /etc/gatus
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: 0755

- name: Copy template to host 
  template:
    src: templates/config.yml.j2
    path: /etc/gatus/config.yml
